spring:
  application:
    name: webflux-tutorial

external:
  demo01:
    productsUri: http://localhost:7070/demo01/products
    productsNotoriousUri: http://localhost:7070/demo01/products/notorious
